version: 0.1
phases:
  install:
   runtime-versions:
      java: openjdk11
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-851637134538 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
